steps:

-   name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
         echo deployer | ssh deployer@34.86.172.147 /home/suman_gautam/run.sh;

options:
    logging: CLOUD_LOGGING_ONLY
