name: E2ETest

on:
  push:
    branches: [main]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: ssh into instance
      run: |
            sudo apt-get install sshpass
            sshpass -p deploying ssh deployer@34.86.172.147 /home/deploying/run.sh
