name: E2ETest

on:
  push:
    branches: [main]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: ssh into instance
      run: |
            sshpass -p deploying ssh deploying@34.86.172.147
