name: E2ETest

on:
  push:
    branches: [ e2eTestCI ]
    # paths:
    #   - 'cmd'
  pull_request:
    branches: [ e2eTestCI ]
    # paths:
    #   - 'cmd'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: ssh into instance
      run: |
            apt-get install sshpass
            sshpass -p deploying ssh deployer@34.86.172.147 /home/deploying/run.sh